apiVersion: apps/v1
kind: Deployment
metadata:
  name: ezeeai-deployment
  labels:
    app: ezeeai
spec:
  replicas: 3
  selector:
    matchLabels:
      app: ezeeai
  template:
    metadata:
      labels:
        app: ezeeai
    spec:
      containers:
      - name: ezeeai
        image: machine2learn/ezeeai:1.0.0
        ports:
        - containerPort: 5000 
        volumeMounts:
          # name must match the volume name below
          - name: my-pvc-nfs
            mountPath: "/tmp/data"
      volumes:
      - name: my-pvc-nfs
        persistentVolumeClaim:
          claimName: nfs
