apiVersion: apps/v1
kind: Deployment
metadata:
  name: register-deployment
  labels:
    app: register
spec:
  replicas: 1
  selector:
    matchLabels:
      app: register
  template:
    metadata:
      labels:
        app: register
    spec:
      containers:
      - name: register
        image: eu.gcr.io/metal-imprint-238115/register:1.0.0
        imagePullPolicy: Always
        ports:
        - containerPort: 5000 
        env:
          - name: DB_USER
            valueFrom:
              secretKeyRef:
                name: db-user-pass
                key: username
          - name: DB_PASSWORD 
            valueFrom:
              secretKeyRef:
                name: db-user-pass
                key: password
          - name: DB_HOST
            value: 127.0.0.1:5432
          - name: SECRET_KEY
            value: machine2learn
          - name: DB_NAME
            valueFrom:
              secretKeyRef:
                name: db-user-pass
                key: db
          - name: SENDGRID_API_KEY
            valueFrom:
              secretKeyRef:
                name: sendgrid-api-key
                key: api_key 
      - name: cloudsql-proxy
        image: gcr.io/cloudsql-docker/gce-proxy:1.11
        command: ["/cloud_sql_proxy",
                  "-instances=metal-imprint-238115:europe-west1:ezeeaiusers=tcp:5432",
                  "-credential_file=/secrets/cloudsql/credentials.json"]
        # [START cloudsql_security_context]
        securityContext:
          runAsUser: 2  # non-root user
          allowPrivilegeEscalation: false
        # [END cloudsql_security_context]
        volumeMounts:
          - name: cloudsql-instance-credentials
            mountPath: /secrets/cloudsql
            readOnly: true

      volumes:
      - name: cloudsql-instance-credentials
        secret:
            secretName: cloudsql-instance-credentials
